### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by Gitcrafter** [Seraphaestus/FactoriOres#3]
Hello, after trying your mod out, I have to say it looks great, but I noticed some problems:

First: a miner, that is extracting fluids, will fill a tank even if there is less than 1000 mB space in the tank, deleting any fluid, that doesn´t fits in the tank

Second: the recipe to craft the Coal Nuggets into Coal is missing

**Comment by Seraphaestus** [comment]
Thank you!
1. Ah, I forgot that was an issue, thanks for bringing it to my attention. It should be fixed, albeit the miner will still consume fuel/energy while the tank is full, just not void the excess fluid. You can setup redstone to disable the miners when your tank is full, though.
2. This is intentional. Coal ore deposits drop coal by default, and coal nuggets are mainly to allow you to configure it so the miner is 8x as fast, such that an extracted nugget powers the miner for the same amount of time, but only smelts one item in furnaces. If you're going to be configuring things anyway, it's easy to add a recipe to convert between coal and coal nuggets. The name 'nugget' may have been a bit of a misnomer but it seemed fitting
